approve:
- commandHelpLink: ""
  repos:
  - openshift/frr
  require_self_approval: false
label:
  restricted_labels:
    openshift/frr:
    - allowed_users:
      - russellb
      - fedepaol
      - msherif1234
      - oribon
      label: backport-risk-assessed
    - allowed_users:
      - mffiedler
      - gsr-shanks
      - rbbratta
      - zhaozhanqi
      - weliang1
      - anuragthehatter
      - huiran0826
      - asood-rh
      - yingwang-0320
      - qiowang721
      - jechen0648
      - gkopels
      - evgenLevin
      label: cherry-pick-approved
lgtm:
- repos:
  - openshift/frr
  review_acts_as_lgtm: true
plugins:
  openshift/frr:
    plugins:
    - approve
